---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
# yamllint disable rule:line-length
# yamllint disable rule:comments
name: Nix
on:
  pull_request:
    paths:
      - "flake.nix"
      - "flake.lock"
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22

      - name: Check
        run: nix flake check --all-systems --no-build
